name: "ChatGPT Reviewer"
author: "Pengfei Ni"
description: "Automated pull requests reviewing and issues triaging with ChatGPT"
inputs:
  GITHUB_TOKEN:
    description: "Github token used to send out review comments"
    required: true
  OPENAI_API_KEY:
    description: "API key used to invoke OpenAI"
    required: true
  OPENAI_API_BASE:
    description: "API based used to access [Azure] OpenAI API"
    required: false
  model:
    description: "OpenAI model name"
    default: "gpt-3.5-turbo"
    required: false
  blocking:
    description: "Blocking the pull requests on OpenAI failures"
    default: 'False'
    required: false
  temperature:
    description: "Temperature for the model"
    default: '0.2'
    required: false
  frequency_penalty:
    description: "Frequency penalty for the model"
    default: '0'
    required: false
  presence_penalty:
    description: "Presence penalty for the model"
    default: '0'
    required: false
  review_per_file:
    description: "Send out review requests per file"
    default: 'False'
    required: false
  comment_per_file:
    description: "Post review comments per file"
    default: 'True'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --model=${{ inputs.model }}
  - --temperature=${{ inputs.temperature }}
  - --frequency-penalty=${{ inputs.frequency_penalty }}
  - --presence-penalty=${{ inputs.presence_penalty }}
  - --review-per-file=${{ inputs.review_per_file }}
  - --comment-per-file=${{ inputs.comment_per_file }}
  - --blocking=${{ inputs.blocking }}
branding:
  icon: 'compass'
  color: 'blue'